# Set the following environment variables in the bitbucket pipelines settings:
#  AWS_ACCESS_KEY_ID
#  AWS_SECRET_ACCESS_KEY
#  AWS_ACCOUNT_ID
#  AWS_DEFAULT_REGION
#  IMAGE_NAME
#  ECS_CLUSTER
#
# For multiple environments in the same pipeline, create multiple variables and
# add "ENV_" in front of the variable such as: DEV_AWS_ACCESS_KEY_ID
#
# Copy the task-definition from ./deployments/demo.json to
# ./deployments/$IMAGE_NAME.json and change the it to fit your purposes.

image: atlassian/default-image:2
# testing new image

#image:
#  name: 145601632047.dkr.ecr.eu-west-1.amazonaws.com/bitbucketbuild
#  aws:
#    access-key: $AWS_ACCESS_KEY_ID
#    secret-key: $AWS_SECRET_ACCESS_KEY
pipelines:
  default:
  - step:
      name: Build image and test
      services:
      - docker
      caches:
      - docker
      script:
      - DOCKERTAG=$(echo $BITBUCKET_BUILD_NUMBER | sed 's/://')
      - docker build . -t $IMAGE_NAME:${DOCKERTAG}-build
      - docker build . -t $IMAGE_NAME:${DOCKERTAG}
      - docker save -o image.tar $IMAGE_NAME:${DOCKERTAG}
      artifacts:
      - image.tar
  - step:
      name: Push to ECR
      services:
      - docker
      caches:
      - docker
      script:
      - docker load -i image.tar
#      - apt-get update && apt-get install -y python-dev jq
#      - |
#        curl -O https://bootstrap.pypa.io/get-pip.py
#        python get-pip.py
#      - pip install awscli
      - #export AWS_ACCESS_KEY_ID="$DEV_AWS_ACCESS_KEY_ID" && export AWS_SECRET_ACCESS_KEY="$DEV_AWS_SECRET_ACCESS_KEY"
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - DOCKERTAG=$(echo $BITBUCKET_BUILD_NUMBER | sed 's/://')
      - echo "Currently building $IMAGE_NAME:$DOCKERTAG"
      - REPOSITORY="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME:$DOCKERTAG"
      - docker tag $IMAGE_NAME:$DOCKERTAG $REPOSITORY
      - docker push $REPOSITORY
  - step:
      name: Deploy to development
      deployment: staging
      services:
      - docker
      caches:
      - docker
      script:
#      - apt-get update && apt-get install -y python-dev jq
#      - |
#        curl -O https://bootstrap.pypa.io/get-pip.py
#        python get-pip.py
#      - pip install awscli
      - #export AWS_ACCESS_KEY_ID="$DEV_AWS_ACCESS_KEY_ID" && export AWS_SECRET_ACCESS_KEY="$DEV_AWS_SECRET_ACCESS_KEY"
      - export ENVIRONMENT="dev"
      - DOCKERTAG=$(echo $BITBUCKET_BUILD_NUMBER | sed 's/://')
      - export DOCKER_IMAGE="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME:$DOCKERTAG"
      - chmod +x scripts/update_task.sh
      - TASK_NAME=$IMAGE_NAME scripts/update_task.sh
options:
  docker: true